### ISSUE TITLE
Is the conversion done right? 

### ISSUE THREAD

**Issue by SAThomsen** [im7mortal/UTM#2]
Hey guys, 

nice library easy to use, thank you for sharing:) I'm intending to use the library to convert latitude and longitude coordinates in Denmark, ie.UTM zone 32U. 

https://epsg.io/ as a benchmark I've created some tests to make sure that the conversions happen as expected. However, I don't get the expected results. I'm not sure if I missed something or there is a bug. 

Maybe you can see what's going on. 

With northing True i get the following, where x and y is the output from FromLatLon()

```bash
longitude: 12.563896, x = 346855.561137268, want 724098.71
latitude: 55.686714, y = 6.1739023650601385e+06, want 6.17717561e+06
```
[epsg.io Equivalent](https://epsg.io/transform#s_srs=4326&t_srs=23032&x=12.5638961&y=55.6867139)

Have I missed something?

**Comment by im7mortal** [comment]
Hi @SAThomsen !
I ported an implementation from [python UTM library](https://github.com/Turbo87/utm).
```python
import utm
print(utm.from_latlon(55.686714, 12.563896))

> (346855.561137268, 6173902.3650601385, 33, 'U'
```
Go match with python implementation.

I checked couple of online converters.
Some of them match to go UTM result.
- http://www.rcn.montana.edu/resources/converter.aspx
- http://home.hiwaay.net/~taylorc/toolbox/geography/geoutm.html

But some resources return what you expect (724014.44, 6176970.19, 32U)
- https://www.latlong.net/lat-long-utm.html

Unfortunately I don't have deep knowledge of this subject.
It would be awesome if you would explain it when you will have figured out it.

**Comment by SAThomsen** [comment]
I think it has to do with the Datum that I use ie. Datum 50. So the full format I'm trying to convert to is UTM32N Datum 50. I'm also no expert at all, but looking around it seems that Datum 50 is a reference point/vector([link](https://en.wikipedia.org/wiki/Datum_reference)).
Although I'm not quite sure what it means for the conversions.
