### ISSUE TITLE
Releases >v1.2.0 can not be imported

### ISSUE THREAD

**Issue by ericwenn** [im7mortal/UTM#5]
The tags for releases after `v1.2.0` omit the `v`-prefix, and can not be imported by other go modules.
For example attempting to `go get` latest version (1.3.0) fails:
```shell
$ go get github.com/im7mortal/UTM@v1.3.0
go: github.com/im7mortal/UTM@v1.3.0: invalid version: unknown revision v1.3.0
```

Likely it should be sufficient to retag the relevant commits with a tag name that include `v`-prefix, for example `1.3.0 -> v1.3.0`.

**Comment by im7mortal** [comment]
@ericwenn Thank you for the suggestion

I didn't push `v-` as  the semver suggest do not use it. 
Anyway I just pushed it. 

Please close the issue if it fix the problem :)

**Comment by ericwenn** [comment]
Thanks for quick response and fix @im7mortal! :medal_sports: 
`go get` on v1.3.0 works as it should now
